name: 'Windows signtool.exe code sign action'
description: 'Sign a file with a pfx certificate.'
branding:
  icon: 'award'
  color: 'blue'
inputs:
  certificate:
    description: 'The base64 encoded certificate.'
    required: true
  folder:
    description: 'The folder that contains the files to sign.'
    required: true
  recursive:
    description: 'Recursively search for supported files.'
    required: false
  password:
    description: 'Password to decrypt and import the certificate'
    required: true
  certificatesha1:
    description: 'The sha1 or fingerprint of the certificate'
    required: false
  certificatename:
    description: 'The Name of the certificate'
    required: false
  description:
    description: 'Description of the signed content (signtool /d flag)'
    required: false
  timestampUrl:
    description: 'URL of the timestamp server'
    required: false
    default: 'http://timestamp.digicert.com'

runs:
  using: 'node20'
  main: 'dist/index.js'
